### ISSUE TITLE
Module loader support

### ISSUE THREAD

**Issue by livtanong** [andrewchambers/janet-jdn#1]
What is your opinion about a module loader for jdn? I wrote one for my personal project, which, when passed a jdn via `import`, assigns that value to the symbol `value`.

e.g.
```
(import data/schools )

schools/value ## the jdn data
```
The usecase is in the event that one wants to make a system that can be extended with jdn data rather than janet files, and you want to use this data in compile-time rather than runtime.

I am deciding whether to publish this as a separate library, but I think it makes sense to be packaged with this (because after all, it's the jdn lib). Is this something you are interested in? If so, I'll open a PR.

**Comment by pepe** [comment]
I am not sure about inclusion of this here (nor my opinion maters), but have you looked at https://janet-lang.org/api/module.html you can do easily things like this with the functionality. The best example beeing (for me anyway) Mendoza. For example: https://github.com/bakpakin/mendoza/blob/master/mendoza/markup.janet

Also I do not know how you implemented this functionality, so maybe you already know this. For me this is one of the Janet super powers for DSL.

**Comment by andrewchambers** [comment]
@levitanong is value a single jdn value? or an array of jdn data?

**Comment by livtanong** [comment]
@pepe yeah, I definitely use janet's module API.
@andrewchambers value is a single jdn value, but if the jdn data itself is already an array, then the value is the array, right? :P
The code is super simple:
```
(import jdn)

(defn load-jdn
  [path args]
  (let [jdn-string (slurp path)
        jdn-value (jdn/decode jdn-string)
        # We want to quote the jdn data structure so that it doesn't get evaluated
        # We do, however, want the `def` evaluated.
        wrapped-value (quasiquote (def value '(unquote jdn-value)))
        serialized-value (string/format "%j" wrapped-value)
        temp-file (file/write (file/temp) serialized-value)]
    # Necessary to seek back to 0 otherwise, dofile will try to read from the very end, and get nothing.
    (file/seek temp-file :set 0)
    # dofile automatically closes the file
    (dofile temp-file (splice args))
    ))

(module/add-paths ".jdn" :jdn)
(put module/loaders :jdn load-jdn)
```

I'm also currently thinking about making a version of this that accepts a path to a _directory_ of JDN files, and then it'll produce  either bindings for the data in each file, or a single binding that's an array of the data within those files.

**Comment by andrewchambers** [comment]
There is a simpler way to implement this, no need for temp files, you can simply return a table in the loader. You must return it like this:

```
(defn load-jdn
  [path args]
  @{'value @{:value (jdn/decode (slurp path))}})
```
(Untested, but something like this should work).

That being said, I'm not sure I want to add a loader to this package as i feel it might be a rare use case.

**Comment by livtanong** [comment]
Ooh! Thanks so much for the feedback! No problem, one more repo for me :D
